cdef double[::1] softmax(double[::1] x)
cdef double sigmoid(double x)
cdef double logit(double x)
cdef double dot(double[::1] v1, double[::1] v2)
cdef double vec_sum(double[::1] v1)
cdef double[::1] elementwise_add_mult(double[::1] v1, double[::1] v2, double s)
cdef double[::1] clip_list(double[::1] a, double min_value, double max_value)
cdef double c_max(double[::1] x)
cdef double clip(double a, double min_value, double max_value)
