cdef double sigmoid(double x)
cdef double logit(double x)
cdef double dot(double[::1] v1, double[::1] v2, int n_threads)
cdef double mt_sum(double[::1] v1, int n_threads)
cdef double[::1] elementwise_add_mult(double[::1] v1, double[::1] v2, double s, int n_threads)
cdef double clip(double a, double min_value, double max_value)
